{% set version = "13.4.59" %}
{% set arm_variant_type = arm_variant_type | default("sbsa") %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [linux and aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

{% set soname = version.split(".")[0] %}

{% set sha256 = "50c80f63663d9ba06d1323cef9195397706db23b8e1083f54e218e93071fa673" %}  # [linux64]
{% set sha256 = "60f86b368c4fa6cfc4c0f8121258242ddc8a4316d789916f943b2e5b444572dd" %}  # [linux and aarch64]
{% set sha256 = "69999f94eb64361a5f1444e6a2dbd57574e645ece02a8fd4d82cea0dda7e92c1" %}  # [win64]
{% set sha256 = "683c0e8dd0d7dc97c843411f0caa3ebe618f62560bf3e8f21b71a6eb8acf8422" %}  # [win and arm64]

package:
  name: cuda-tileiras-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_tileiras/{{ platform }}/cuda_tileiras-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1  # [linux]

outputs:
  - name: cuda-tileiras
    build:
      binary_relocation: false
      script:                        # [win]
         - move bin\* %LIBRARY_BIN%  # [win]
    files:             # [linux]
      - bin/tileiras   # [linux]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - arm-variant * {{ arm_variant_type }}  # [linux and aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - cuda-nvcc-tools
        - cuda-nvvm-impl
    test:
      commands:
        - test -f $PREFIX/bin/tileiras                    # [linux]
        - if not exist %LIBRARY_BIN%\tileiras.exe exit 1  # [win]
        - tileiras --version

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: TileIR is a portable and language agnostic intermediate representation for CUDA kernels
  description: With Tile IR, we introduce a new operation set and programming model to retain CUDA’s performance across architectures while regaining portability and improving productivity for developers using matrix operations on new architectures. We virtualize tensor-cores and their associated programming model to the
    point that we can innovate new approaches in hardware without invalidating investments in software.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  feedstock-name: cuda-tileiras
  recipe-maintainers:
    - conda-forge/cuda
